[workspace]
resolver = "3"
members = [
    "common",
    "microbit_v2",
]

[workspace.dependencies]
common = { path = "./common" }

[profile.dev]
debug = true
lto = true
opt-level = 3

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
