[package]
name = "cookie-monster-rs"
version = "0.1.0"
authors = ["Alex Payment <3332420+AlexPayment@users.noreply.github.com>"]
edition = "2021"
repository = "https://github.com/AlexPayment/cookie-monster-rs/"

[dependencies]
cortex-m-rt = "0.7.3"
panic-rtt-target = { version =  "0.1.2", features = ["cortex-m"] }
rtt-target = { version =  "0.3.1", features = ["cortex-m"] }

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
