[package]
name = "cookie-monster-rs"
version = "0.1.0"
authors = ["Alex Payment <3332420+AlexPayment@users.noreply.github.com>"]
edition = "2021"
repository = "https://github.com/AlexPayment/cookie-monster-rs/"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
microbit-v2 = "0.13.0"
panic-rtt-target = { version =  "0.1.2", features = ["cortex-m"] }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
rtt-target = "0.5.0"
ws2812-spi = "0.4.0"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
