[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --log-format defmt"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[build]
target = "xtensa-esp32-none-elf"

[env]
DEFMT_LOG="debug"

[unstable]
build-std = ["core"]
