[package]
name = "cookie-monster-common"
version = "0.1.0"
authors = ["Alex Payment <3332420+AlexPayment@users.noreply.github.com>"]
edition = "2024"
description = "Common code for Cookie Monster"
repository = "https://github.com/AlexPayment/cookie-monster-rs/"
license = "MIT"
publish = false
